### ISSUE TITLE
Cookie capturing vulnerability 

### ISSUE THREAD

**Issue by kesara** [inveniosoftware/flask-security-fork#41]
This might be a issue with flask-login.
The login out removes the session cookies, but if it's captured before removal, it can be used to access the service as authenticated user.

To recreate:
* Login
* Capture cookie through a browser plugin or a man in the middle proxy
* Logout
* Send a request with captured cookie
* Able to access service as an authenticated user

I found that with `SECURITY_TRACKABLE` enabled, `flask-login.login_fresh()` could identify if the session is stale which checks the User-Agent, IP address etc.
But if the request is coming from the same IP address and same User-Agent,  flask-login still doesn't identify it as stale.

**Comment by lnielsen** [comment]
Thanks for reporting the issue. We are closing this fork, so it's better if you report it upstream on mattupstate/flask-security

Isn't this issue more a by product of Flask's client side session management than a security issue. E.g. in inveniosoftware/invenio-accounts we're storing sessions server-side (using Flask-KVSessions) and removing the sessions upon logout (or if e.g. an admin deactivates a user), hence if you logout the session can't be reused like you have  described.

**Comment by kesara** [comment]
@lnielsen Thanks, storing sessions servers-side is something to think about.

I've reported this on flask-security: https://github.com/mattupstate/flask-security/issues/665
