### ISSUE TITLE
Email confirmation behavior

### ISSUE THREAD

**Issue by kesara** [inveniosoftware/flask-security-fork#42]
At the moment confirmation token can be logs user in automatically.
I suggest this behavior should be, so this can be configured as required.

Other issue with the current confirmation tokens is they can be reused to login without using password as long as that token is not expired.

**Comment by lnielsen** [comment]
@kesara Thanks for reporting the issue. Can you please report it upstream - we're closing down this fork, as now there is a v3.0.0 release of flask-security.

**Comment by kesara** [comment]
@lnielsen Great, didn't knew flask-security is active. ta.

**Comment by kesara** [comment]
Reported upstream: https://github.com/mattupstate/flask-security/issues/662
