### ISSUE TITLE
Allow optional `extra_validators` parameter in `validate` methods of `forms.py`

### ISSUE THREAD

**Issue by GraemeWatt** [inveniosoftware/flask-security-fork#51]
This package requires `Flask-WTF>=1.0.0`, but it breaks with the latest Flask-WTF 1.1.0 released yesterday, where an error message `TypeError: validate() takes 1 positional argument but 2 were given` is obtained from this line:

https://github.com/inveniosoftware/flask-security-fork/blob/3001b0785d9ee769dae52484657e37e2733505db/flask_security/views.py#L52

The failure is due to a change introduced in wtforms/flask-wtf#479.  To fix the problem, an optional argument `extra_validators=None` should be added to each of the `validate` methods in [`forms.py`](https://github.com/inveniosoftware/flask-security-fork/blob/master/flask_security/forms.py).  Alternatively, add `**kwargs` to the `validate` methods as done in Flask-Middleware/flask-security#566.  Until a new fixed release is made of this package, it will be necessary to pin `Flask-WTF<1.1.0`.

**Comment by kpsherva** [comment]
the issue was introduced by broken compatibility in flask-wtf v1.1.0. There is already patch (v1.1.1) provided which fixes the method signature, therefore I am closing the issue

**Comment by GraemeWatt** [comment]
Flask-WTF 1.1.0 gives an error message `TypeError: validate() got an unexpected keyword argument 'extra_validators'`.  Please reopen this issue.  You need to replace `validate(self)` with `validate(self, **kwargs)` four times in [`forms.py`](https://github.com/inveniosoftware/flask-security-fork/blob/master/flask_security/forms.py) and release a new version of this package, then bump the version installed by `invenio-accounts`.

**Comment by GraemeWatt** [comment]
This issue was addressed by PR #52 and I confirm that the release v3.1.4 works.  You might want to change [`Flask-Security-Invenio>=3.1.3`](https://github.com/inveniosoftware/invenio-accounts/blob/c62256bae4e61f81c82fa9295155d41bfa986f91/setup.cfg#L33) to `Flask-Security-Invenio>=3.1.4` in the next release of `invenio-accounts`.
